framework:
    workflows:
        tagging:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
            supports:
                - 'Akeneo\Domain\Model\TaggingProcess'
            initial_place: 'tagging_process_started'
            places:
                - 'tagging_process_started'
                - 'helm_onboarder_pull_request_opened'
                - 'helm_onboarder_pull_request_closed'
                - 'dev_environment_deployed'
                - 'dev_environment_rejected'
                - 'dev_environment_validated'
                - 'pim_onboarder_bundle_tagged'
                - 'pim_enterprise_cloud_updated'
                - 'middleware_tagged'
                - 'overseer_tagged'
                - 'supplier_onboarder_tagged'
                - 'middleware_docker_image_built'
                - 'overseer_docker_image_built'
                - 'supplier_onboarder_docker_image_built'
                - 'helm_onboarder_values_updated'
                - 'helm_onboarder_tagged'
                - 'helm_onboarder_chart_packaged'
            transitions:
                open_helm_onboarder_pull_request:
                    from: 'tagging_process_started'
                    to: 'helm_onboarder_pull_request_opened'
                deploy_dev_environment:
                    from: 'helm_onboarder_pull_request_opened'
                    to: 'dev_environment_deployed'
                reject_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_rejected'
                close_helm_onboarder_pull_request:
                    from: 'dev_environment_rejected'
                    to: 'helm_onboarder_pull_request_closed'
                validate_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_validated'
                tag_pim_onboarder_bundle:
                    from: 'dev_environment_validated'
                    to: 'pim_onboarder_bundle_tagged'
                update_pim_enterprise_cloud:
                    from: 'pim_onboarder_bundle_tagged'
                    to: 'pim_enterprise_cloud_updated'
                tag_middleware:
                    from: 'dev_environment_validated'
                    to: 'middleware_tagged'
                tag_overseer:
                    from: 'dev_environment_validated'
                    to: 'overseer_tagged'
                tag_supplier_onboarder:
                    from: 'dev_environment_validated'
                    to: 'supplier_onboarder_tagged'
                build_middleware_docker_image:
                    from: 'middleware_tagged'
                    to: 'middleware_docker_image_built'
                build_overseer_docker_image:
                    from: 'overseer_tagged'
                    to: 'overseer_docker_image_built'
                build_supplier_onboarder_docker_image:
                    from: 'supplier_onboarder_tagged'
                    to: 'supplier_onboarder_docker_image_built'
                update_helm_onboarder_values:
                    from: ['middleware_docker_image_built', 'overseer_docker_image_built', 'supplier_onboarder_docker_image_built']
                    to: 'helm_onboarder_values_updated'
                tag_helm_onboarder:
                    from: 'helm_onboarder_values_updated'
                    to: 'helm_onboarder_tagged'
                package_helm_onboarder_chart:
                    from: 'helm_onboarder_tagged'
                    to: 'helm_onboarder_chart_packaged'
