framework:
    workflows:
        tagging:
            type: 'workflow'
            marking_store:
                type: 'multiple_state'
                arguments:
                    - 'places'
            supports:
                - 'Akeneo\Domain\Tagging\TaggingProcess'
            initial_place: 'tagging_process_started'
            places:
                - 'tagging_process_started'
                - 'pim_enterprise_cloud_git_repository_cloned'
                - 'middleware_git_repository_cloned'
                - 'overseer_git_repository_cloned'
                - 'supplier_onboarder_git_repository_cloned'
                - 'pim_enterprise_cloud_prepared_for_dev'
                - 'dev_middleware_docker_image_built'
                - 'dev_overseer_docker_image_built'
                - 'dev_supplier_onboarder_docker_image_built'
                - 'dev_middleware_docker_image_pushed'
                - 'dev_overseer_docker_image_pushed'
                - 'dev_supplier_onboarder_docker_image_pushed'
                - 'pim_enterprise_cloud_preparation_aborted'
                - 'dev_environment_deployed'
                - 'dev_environment_rejected'
                - 'dev_environment_validated'
                - 'pim_onboarder_bundle_git_repository_cloned'
                - 'pim_onboarder_bundle_tagged'
                - 'pim_enterprise_cloud_updated_for_production'
                - 'middleware_tagged'
                - 'overseer_tagged'
                - 'supplier_onboarder_tagged'
                - 'middleware_docker_image_tagged_for_prod'
                - 'overseer_docker_image_tagged_for_prod'
                - 'supplier_onboarder_docker_image_tagged_for_prod'
                - 'helm_onboarder_values_updated'
                - 'helm_onboarder_tagged'
                - 'helm_onboarder_chart_packaged'
            transitions:
                clone_pim_enterprise_cloud_git_repository:
                    from: 'tagging_process_started'
                    to: 'pim_enterprise_cloud_git_repository_cloned'
                clone_middleware_git_repository:
                    from: 'tagging_process_started'
                    to: 'middleware_git_repository_cloned'
                clone_overseer_git_repository:
                    from: 'tagging_process_started'
                    to: 'overseer_git_repository_cloned'
                clone_supplier_onboarder_git_repository:
                    from: 'tagging_process_started'
                    to: 'supplier_onboarder_git_repository_cloned'
                prepare_pim_enterprise_cloud_for_dev:
                    from: 'pim_enterprise_cloud_git_repository_cloned'
                    to: 'pim_enterprise_cloud_prepared_for_dev'
                build_dev_middleware_docker_image:
                    from: 'middleware_git_repository_cloned'
                    to: 'dev_middleware_docker_image_built'
                build_dev_overseer_docker_image:
                    from: 'overseer_git_repository_cloned'
                    to: 'dev_overseer_docker_image_built'
                build_dev_supplier_onboarder_docker_image:
                    from: 'supplier_onboarder_git_repository_cloned'
                    to: 'dev_supplier_onboarder_docker_image_built'
                push_dev_middleware_docker_image:
                    from: 'dev_middleware_docker_image_built'
                    to: 'dev_middleware_docker_image_pushed'
                push_dev_overseer_docker_image:
                    from: 'dev_overseer_docker_image_built'
                    to: 'dev_overseer_docker_image_pushed'
                push_dev_supplier_onboarder_docker_image:
                    from: 'dev_supplier_onboarder_docker_image_built'
                    to: 'dev_supplier_onboarder_docker_image_pushed'
                deploy_dev_environment:
                    from: ['pim_enterprise_cloud_prepared_for_dev', 'dev_middleware_docker_image_pushed', 'dev_overseer_docker_image_pushed', 'dev_supplier_onboarder_docker_image_pushed']
                    to: 'dev_environment_deployed'
                reject_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_rejected'
                abort_pim_enterprise_cloud_preparation:
                    from: 'dev_environment_rejected'
                    to: 'pim_enterprise_cloud_preparation_aborted'
                validate_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_validated'
                clone_pim_onboarder_bundle_git_repository:
                    from: 'dev_environment_validated'
                    to: 'pim_onboarder_bundle_git_repository_cloned'
                tag_pim_onboarder_bundle:
                    from: 'pim_onboarder_bundle_git_repository_cloned'
                    to: 'pim_onboarder_bundle_tagged'
                update_pim_enterprise_cloud_for_prod:
                    from: ['pim_onboarder_bundle_tagged', 'pim_enterprise_cloud_prepared_for_dev']
                    to: 'pim_enterprise_cloud_updated_for_production'
                tag_middleware:
                    from: 'dev_environment_validated'
                    to: 'middleware_tagged'
                tag_overseer:
                    from: 'dev_environment_validated'
                    to: 'overseer_tagged'
                tag_supplier_onboarder:
                    from: 'dev_environment_validated'
                    to: 'supplier_onboarder_tagged'
                tag_middleware_docker_image_for_prod:
                    from: 'middleware_tagged'
                    to: 'middleware_docker_image_tagged_for_prod'
                tag_overseer_docker_image_for_prod:
                    from: 'overseer_tagged'
                    to: 'overseer_docker_image_tagged_for_prod'
                tag_supplier_onboarder_docker_image_for_prod:
                    from: 'supplier_onboarder_tagged'
                    to: 'supplier_onboarder_docker_image_tagged_for_prod'
                update_helm_onboarder_values:
                    from: ['pim_enterprise_cloud_updated_for_production', 'middleware_docker_image_tagged_for_prod', 'overseer_docker_image_tagged_for_prod', 'supplier_onboarder_docker_image_tagged_for_prod']
                    to: 'helm_onboarder_values_updated'
                tag_helm_onboarder:
                    from: 'helm_onboarder_values_updated'
                    to: 'helm_onboarder_tagged'
                package_helm_onboarder_chart:
                    from: 'helm_onboarder_tagged'
                    to: 'helm_onboarder_chart_packaged'
