framework:
    workflows:
        tagging:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
            supports:
                - 'Akeneo\Domain\Model\TaggingProcess'
            initial_place: 'tagging_process_started'
            places:
                - 'tagging_process_started'
                - 'pim_enterprise_cloud_prepared_for_dev'
                - 'middleware_docker_image_built_for_dev'
                - 'overseer_docker_image_built_for_dev'
                - 'supplier_onboarder_docker_image_built_for_dev'
                - 'pim_enterprise_cloud_preparation_aborted'
                - 'dev_environment_deployed'
                - 'dev_environment_rejected'
                - 'dev_environment_validated'
                - 'pim_onboarder_bundle_tagged'
                - 'pim_enterprise_cloud_updated_for_production'
                - 'middleware_tagged'
                - 'overseer_tagged'
                - 'supplier_onboarder_tagged'
                - 'middleware_docker_image_tagged_for_prod'
                - 'overseer_docker_image_tagged_for_prod'
                - 'supplier_onboarder_docker_image_tagged_for_prod'
                - 'helm_onboarder_values_updated'
                - 'helm_onboarder_tagged'
                - 'helm_onboarder_chart_packaged'
            transitions:
                prepare_pim_enterprise_cloud_for_dev:
                    from: 'tagging_process_started'
                    to: 'pim_enterprise_cloud_prepared_for_dev'
                build_middleware_docker_image_for_dev:
                    from: 'tagging_process_started'
                    to: 'middleware_docker_image_built_for_dev'
                build_overseer_docker_image_for_dev:
                    from: 'tagging_process_started'
                    to: 'overseer_docker_image_built_for_dev'
                build_supplier_onboarder_docker_image_for_dev:
                    from: 'tagging_process_started'
                    to: 'supplier_onboarder_docker_image_built_for_dev'
                deploy_dev_environment:
                    from: ['pim_enterprise_cloud_prepared_for_dev', 'middleware_docker_image_built_for_dev', 'overseer_docker_image_built_for_dev', 'supplier_onboarder_docker_image_built_for_dev']
                    to: 'dev_environment_deployed'
                reject_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_rejected'
                abort_pim_enterprise_cloud_preparation:
                    from: 'dev_environment_rejected'
                    to: 'pim_enterprise_cloud_preparation_aborted'
                validate_dev_environment:
                    from: 'dev_environment_deployed'
                    to: 'dev_environment_validated'
                tag_pim_onboarder_bundle:
                    from: 'dev_environment_validated'
                    to: 'pim_onboarder_bundle_tagged'
                update_pim_enterprise_cloud_for_prod:
                    from: 'pim_onboarder_bundle_tagged'
                    to: 'pim_enterprise_cloud_updated_for_production'
                tag_middleware:
                    from: 'dev_environment_validated'
                    to: 'middleware_tagged'
                tag_overseer:
                    from: 'dev_environment_validated'
                    to: 'overseer_tagged'
                tag_supplier_onboarder:
                    from: 'dev_environment_validated'
                    to: 'supplier_onboarder_tagged'
                tag_middleware_docker_image_for_prod:
                    from: 'middleware_tagged'
                    to: 'middleware_docker_image_tagged_for_prod'
                tag_overseer_docker_image_for_prod:
                    from: 'overseer_tagged'
                    to: 'overseer_docker_image_tagged_for_prod'
                tag_supplier_onboarder_docker_image_for_prod:
                    from: 'supplier_onboarder_tagged'
                    to: 'supplier_onboarder_docker_image_tagged_for_prod'
                update_helm_onboarder_values:
                    from: ['pim_enterprise_cloud_updated_for_production', 'middleware_docker_image_tagged_for_prod', 'overseer_docker_image_tagged_for_prod', 'supplier_onboarder_docker_image_tagged_for_prod']
                    to: 'helm_onboarder_values_updated'
                tag_helm_onboarder:
                    from: 'helm_onboarder_values_updated'
                    to: 'helm_onboarder_tagged'
                package_helm_onboarder_chart:
                    from: 'helm_onboarder_tagged'
                    to: 'helm_onboarder_chart_packaged'
