framework:
    workflows:
        onboarder_release:
            type: 'workflow'
            marking_store:
                type: 'multiple_state'
                arguments:
                    - 'places'
            supports:
                - 'Akeneo\Application\Onboarder\OnboarderRelease'
            initial_place: 'tagging_process_started'
            places:
                - 'tagging_process_started'
                - 'pim_enterprise_cloud_download_process_started'
                - 'pim_enterprise_cloud_archive_downloaded'
                - 'pim_enterprise_cloud_prepared_for_dev'
                - 'pim_enterprise_cloud_preparation_aborted'
                - 'dev_environment_deployed'
                - 'validation_process_started'
                - 'rejection_process_started'
                - 'dev_environment_rejected'
                - 'dev_environment_validated'
                - 'pim_onboarder_bundle_tagging_process_started'
                - 'middleware_tagging_process_started'
                - 'overseer_tagging_process_started'
                - 'supplier_onboarder_bundle_tagging_process_started'
                - 'pim_onboarder_bundle_tagged'
                - 'pim_enterprise_cloud_updated_for_production'
                - 'middleware_tagged'
                - 'overseer_tagged'
                - 'supplier_onboarder_tagged'
                - 'middleware_docker_image_tagged_for_prod'
                - 'overseer_docker_image_tagged_for_prod'
                - 'supplier_onboarder_docker_image_tagged_for_prod'
                - 'helm_onboarder_values_updated'
                - 'helm_onboarder_tagged'
                - 'helm_onboarder_chart_packaged'
            transitions:
                start_download_process:
                    from: 'tagging_process_started'
                    to: 'pim_enterprise_cloud_download_process_started'
                download_pim_enterprise_cloud_archive:
                    from: 'pim_enterprise_cloud_download_process_started'
                    to: 'pim_enterprise_cloud_archive_downloaded'
                prepare_pim_enterprise_cloud_for_dev:
                    from: 'pim_enterprise_cloud_archive_downloaded'
                    to: 'pim_enterprise_cloud_prepared_for_dev'
                deploy_dev_environment:
                    from: 'pim_enterprise_cloud_prepared_for_dev'
                    to: 'dev_environment_deployed'
                start_validation_process:
                    from: 'dev_environment_deployed'
                    to:
                        - 'validation_process_started'
                        - 'rejection_process_started'
                reject_dev_environment:
                    from: 'rejection_process_started'
                    to: 'dev_environment_rejected'
                abort_pim_enterprise_cloud_preparation:
                    from: 'dev_environment_rejected'
                    to: 'pim_enterprise_cloud_preparation_aborted'
                validate_dev_environment:
                    from: 'validation_process_started'
                    to: 'dev_environment_validated'
                start_tagging_process:
                    from: 'dev_environment_validated'
                    to:
                        - 'pim_onboarder_bundle_tagging_process_started'
                        - 'middleware_tagging_process_started'
                        - 'overseer_tagging_process_started'
                        - 'supplier_onboarder_bundle_tagging_process_started'
                tag_pim_onboarder_bundle:
                    from: 'pim_onboarder_bundle_tagging_process_started'
                    to: 'pim_onboarder_bundle_tagged'
                update_pim_enterprise_cloud_for_prod:
                    from:
                        - 'pim_onboarder_bundle_tagged'
                        - 'pim_enterprise_cloud_prepared_for_dev'
                    to: 'pim_enterprise_cloud_updated_for_production'
                tag_middleware:
                    from: 'middleware_tagging_process_started'
                    to: 'middleware_tagged'
                tag_overseer:
                    from: 'overseer_tagging_process_started'
                    to: 'overseer_tagged'
                tag_supplier_onboarder:
                    from: 'supplier_onboarder_bundle_tagging_process_started'
                    to: 'supplier_onboarder_tagged'
                tag_middleware_docker_image_for_prod:
                    from: 'middleware_tagged'
                    to: 'middleware_docker_image_tagged_for_prod'
                tag_overseer_docker_image_for_prod:
                    from: 'overseer_tagged'
                    to: 'overseer_docker_image_tagged_for_prod'
                tag_supplier_onboarder_docker_image_for_prod:
                    from: 'supplier_onboarder_tagged'
                    to: 'supplier_onboarder_docker_image_tagged_for_prod'
                update_helm_onboarder_values:
                    from:
                        - 'pim_enterprise_cloud_updated_for_production'
                        - 'middleware_docker_image_tagged_for_prod'
                        - 'overseer_docker_image_tagged_for_prod'
                        - 'supplier_onboarder_docker_image_tagged_for_prod'
                    to: 'helm_onboarder_values_updated'
                tag_helm_onboarder:
                    from: 'helm_onboarder_values_updated'
                    to: 'helm_onboarder_tagged'
                package_helm_onboarder_chart:
                    from: 'helm_onboarder_tagged'
                    to: 'helm_onboarder_chart_packaged'
