version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - node_modules-{{ .Environment.CACHE_VERSION }}
            - node_modules
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --check-files
      - save_cache:
          key: node_modules-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Create the "reports" folder
          command: mkdir reports
      - run:
          name: Lint CSS code with Stylelint
          command: yarn stylelint
      - run:
          name: Lint JavaScript code with Eslint
          command: yarn eslint -f junit > reports/eslint.xml
      - run:
          name: Build the application
          command: yarn build
      - run:
          name: Configure Git to use a specific SSH key
          command: |
            export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_1f25f8bb595295f6e2f2972f30d4e966 -o UserKnownHostsFile=~/.ssh/known_hosts -o IdentitiesOnly=Yes'
            echo "export GIT_SSH_COMMAND=${GIT_SSH_COMMAND}" >> $BASH_ENV
      - gh-pages/deploy:
          git-email: 'circle-ci@akeneo.com'
          git-user: 'akeneo-circle-ci'
          ssh-fingerprints: '1f:25:f8:bb:59:52:95:f6:e2:f2:97:2f:30:d4:e9:66'
          workspace-root: ~/project
      - store_test_results:
          path: var/tests
      - store_artifacts:
          path: var/tests

workflows:
  pull_request:
    jobs:
      - ready_to_build?:
          type: approval
          filters:
            branches:
              ignore:
                - 'master'
      - test:
          requires:
            - ready_to_build?

  after_merge:
    jobs:
      - ready_to_build?:
          type: approval
          filters:
            branches:
              only:
                - 'master'
