version: 2

jobs:
    setup:
        machine:
            enabled: true
            docker_layer_caching: true
        steps:
            - checkout

workflows:
    version: 2
    pull_request:
        jobs:
            - wait_for_user_approval:
                type: approval
                filters:
                    branches:
                        ignore:
                            - "master"
            - setup:
                requires:
                    - wait_for_user_approval

    nightly:
        triggers:
            - schedule:
                cron: "42 0 * * *"
                filters:
                    branches:
                        only:
                            - "master"
        jobs:
            - setup
