version: 2.1

jobs:
    test:
        machine:
            docker_layer_caching: true
            image: ubuntu-2004:202010-01
        environment:
            CURRENT_USER_IDS: "1001:1002"
        steps:
            - checkout
            - store_test_results:
                path: var/tests
            - store_artifacts:
                path: var/tests

workflows:
    pull_request:
        jobs:
            - wait_for_user_approval:
                type: approval
                filters:
                    branches:
                        ignore:
                            - "master"
            - test:
                requires:
                    - wait_for_user_approval
