version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Create the "reports" folder
          command: mkdir reports
      - run:
          name: Lint JavaScript code with Eslint
          command: yarn eslint -f junit > reports/eslint.xml
      - run:
          name: Try to build the application
          command: yarn build
      - store_test_results:
          path: var/tests
      - store_artifacts:
          path: var/tests

workflows:
  pull_request:
    jobs:
      - ready_to_build?:
          type: approval
          filters:
            branches:
              ignore:
                - 'master'
      - test:
          requires:
            - ready_to_build?
