version: 2

jobs:
    setup:
        machine:
            image: ubuntu-1604:201903-01
        environment:
            CURRENT_IDS: "1001:1002"
        steps:
            - checkout
            - run:
                name: Copy Docker Compose override
                command: cp .circleci/docker-compose.override.yaml.dist docker-compose.override.yaml
            - run:
                name: Create cache directory for composer dependencies
                command: mkdir -p ~/.cache/composer
            - run:
                name: Create configuration directory for composer dependencies
                command: mkdir -p ~/.config/composer
            - restore_cache:
                name: Restore Composer cache
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    - composer-v1-
            - run:
                name: Install dependencies
                command: make install
            - save_cache:
                name: Save Composer cache
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - ~/.cache/composer
            - run:
                name: Create directories for tests results
                command: mkdir -p var/tests/phpspec var/tests/behat var/tests/integration
            - run:
                name: Archive Docker image
                command: docker save -o patoche.tar akeneo/patoche/dev:master
            - persist_to_workspace:
                root: ~/
                paths:
                    - project
                    - patoche.tar

    test:
        machine:
            image: ubuntu-1604:201903-01
        environment:
            CURRENT_IDS: "1001:1002"
        steps:
            - attach_workspace:
                at: ~/
            - run:
                name: Load archived Docker image
                command: docker load -i patoche.tar
            - run:
                name: Check code style
                command: make code-style
            - run:
                name: Execute static analysis
                command: make static-analysis
            - run:
                name: Run phpspec tests
                command: docker-compose run --rm -T php vendor/bin/phpspec run --format=junit > var/tests/phpspec/specs.xml
            - run:
                name: Run acceptance tests
                command: docker-compose run --rm php vendor/bin/behat -p acceptance -f junit -o var/tests/behat -f pretty -o std --colors
            - run:
                name: Run integration tests
                command: docker-compose run --rm php vendor/bin/phpunit --log-junit var/tests/integration/phpunit.xml
            - store_test_results:
                path: var/tests
            - store_artifacts:
                path: var/tests

workflows:
    version: 2
    pull_request:
        jobs:
            - wait_for_user_approval:
                type: approval
                filters:
                    branches:
                        ignore:
                            - "master"
            - setup:
                requires:
                    - wait_for_user_approval
            - test:
                requires:
                    - setup

    nightly:
        triggers:
            - schedule:
                cron: "42 0 * * *"
                filters:
                    branches:
                        only:
                            - "master"
        jobs:
            - setup
            - test:
                requires:
                    - setup
