parameters:
    akeneo.filesystem.default.directory: '%kernel.project_dir%/data/tests'

# TODO: Remove this file once the handler is used in an event subscriber
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Akeneo\Application\Vcs\DownloadArchiveHandler:
        public: true
        arguments:
            - '@Akeneo\Application\Vcs\VcsApiClient'
