services:
    _defaults:
        autowire: false
        autoconfigure: false

    # - APPLICATION SERVICES OVERRIDDEN FOR ACCEPTANCE TESTS - #

    Akeneo\Tests\Acceptance\Deployment\DependencyManager\FakeComposer:
        arguments:
            - !php/const Akeneo\Tests\Acceptance\Context\PrepareForDeploymentContext::PEC_COMPOSER_JSON
    Akeneo\Application\Deployment\DependencyManager: '@Akeneo\Tests\Acceptance\Deployment\DependencyManager\FakeComposer'

    Akeneo\Tests\Acceptance\Vcs\Api\FakeClient:
        arguments:
            - '@League\Flysystem\Filesystem'
    Akeneo\Application\Vcs\VcsApiClient: '@Akeneo\Tests\Acceptance\Vcs\Api\FakeClient'

    # - BEHAT CONTEXTS FOR ACCEPTANCE TESTS - #

    Akeneo\Tests\Acceptance\Context\CommonContext:
        public: true
        arguments:
            - '%akeneo_patoche.application.mapped_branches%'

    Akeneo\Tests\Acceptance\Context\DownloadArchiveContext:
        public: true
        arguments:
            - '@Akeneo\Application\Vcs\DownloadArchiveHandler'
            - '@League\Flysystem\Filesystem'

    Akeneo\Tests\Acceptance\Context\ProposeTagContext:
        public: true
        arguments:
            - '@Akeneo\Application\Vcs\GetNextTagHandler'

    Akeneo\Tests\Acceptance\Context\PrepareForDeploymentContext:
        public: true
        arguments:
            - '@Akeneo\Application\Deployment\PreparePimForDeploymentHandler'
            - '@Akeneo\Tests\Acceptance\Deployment\DependencyManager\FakeComposer'
