services:
    _defaults:
        autowire: false
        autoconfigure: false

    # - APPLICATION SERVICES OVERRIDDEN FOR ACCEPTANCE TESTS - #

    Akeneo\Patoche\Tests\Acceptance\Deployment\DependencyManager\FakeComposerFactory:
        arguments:
            - '@League\Flysystem\Filesystem'
    Akeneo\Patoche\Application\Deployment\DependencyManagerFactory: '@Akeneo\Patoche\Tests\Acceptance\Deployment\DependencyManager\FakeComposerFactory'

    Akeneo\Patoche\Tests\Acceptance\Vcs\Api\FakeClient:
        arguments:
            - '@League\Flysystem\Filesystem'
    Akeneo\Patoche\Application\Vcs\VcsApiClient: '@Akeneo\Patoche\Tests\Acceptance\Vcs\Api\FakeClient'

    # - BEHAT CONTEXTS FOR ACCEPTANCE TESTS - #

    Akeneo\Patoche\Tests\Acceptance\Context\CommonContext:
        public: true
        arguments:
            - '%akeneo_patoche.application.mapped_branches%'

    Akeneo\Patoche\Tests\Acceptance\Context\DownloadArchiveContext:
        public: true
        arguments:
            - '@Akeneo\Patoche\Application\Vcs\DownloadArchiveHandler'
            - '@League\Flysystem\Filesystem'

    Akeneo\Patoche\Tests\Acceptance\Context\ProposeTagContext:
        public: true
        arguments:
            - '@Akeneo\Patoche\Application\Vcs\GetNextTagHandler'

    Akeneo\Patoche\Tests\Acceptance\Context\PrepareForDeploymentContext:
        public: true
        arguments:
            - '@Akeneo\Patoche\Application\Deployment\PreparePimForDeploymentHandler'
            - '@League\Flysystem\Filesystem'
